baseURL = "https://zharmediablog.netlify.app/"
title = "M Azhar Alauddin"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = "Zharmedia"
  description = "Software Engineering Student"
  avatarURL = "/images/avatar1.webp"
  avatarSize = "size-m"
  customHeadHTML = ""
  showPostsOnHomePage = "popular"
  metaKeywords = ["blog", "gokarna", "hugo"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 4

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6
