baseURL = "https://zharmediablog.netlify.app/"
title = "M Azhar Alauddin"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = "Zharmedia"
  description = "Software Engineering Student"
  avatarURL = "/images/avatar.webp"
  avatarSize = "size-m"
  customHeadHTML = ""
  showPostsOnHomePage = "popular"
  metaKeywords = ["blog", "gokarna", "hugo"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

[[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/zharmedia386"
    weight = 5

  [[menu.main]]
    identifier = "instagram"
    pre = "<span data-feather='instagram'></span>"
    url = "https://www.instagram.com/m.azhar.alauddin"
    weight = 6

  [[menu.main]]
    identifier = "linkedin"
    pre = "<span data-feather='linkedin'></span>"
    url = "https://www.linkedin.com/in/m-azhar-alauddin/"
    weight = 7
